import {
  AddressBookIcon,
  AirplaneIcon,
  AirplaneTiltIcon,
  AirplayIcon,
  AlarmIcon,
  AlienIcon,
  ArchiveIcon,
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowDownIcon,
  ArrowFatDownIcon,
  ArrowFatLeftIcon,
  ArrowFatRightIcon,
  ArrowFatUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowsClockwiseIcon,
  ArrowsDownUpIcon,
  ArrowsHorizontalIcon,
  ArrowsLeftRightIcon,
  ArrowsVerticalIcon,
  ArticleIcon,
  AtIcon,
  BabyCarriageIcon,
  BackspaceIcon,
  BagIcon,
  BalloonIcon,
  BarcodeIcon,
  BaseballHelmetIcon,
  BasketIcon,
  BasketballIcon,
  BellIcon,
  BellRingingIcon,
  BellSlashIcon,
  BinocularsIcon,
  BirdIcon,
  BombIcon,
  BoneIcon,
  BookBookmarkIcon,
  BookOpenIcon,
  BookOpenTextIcon,
  BookmarkIcon,
  BookmarksIcon,
  BooksIcon,
  BowlingBallIcon,
  BoxArrowDownIcon,
  BoxArrowUpIcon,
  BoxingGloveIcon,
  BriefcaseIcon,
  BulbIcon,
  BusIcon,
  ButterflyIcon,
  CactusIcon,
  CalculatorIcon,
  CalendarBlankIcon,
  CalendarCheckIcon,
  CalendarDotIcon,
  CalendarDotsIcon,
  CalendarHeartIcon,
  CalendarIcon,
  CameraIcon,
  CarIcon,
  CarProfileIcon,
  CaretCircleDownIcon,
  CaretCircleLeftIcon,
  CaretCircleRightIcon,
  CaretCircleUpDownIcon,
  CaretCircleUpIcon,
  CaretDoubleDownIcon,
  CaretDoubleLeftIcon,
  CaretDoubleRightIcon,
  CaretDoubleUpIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  CatIcon,
  CertificateIcon,
  ChatCircleDotsIcon,
  ChatCircleIcon,
  ChatCircleSlashIcon,
  ChatCircleTextIcon,
  ChatSquareDotsIcon,
  ChatSquareIcon,
  ChatSquareSlashIcon,
  ChatSquareTextIcon,
  ChatsCircleIcon,
  ChatsSquareIcon,
  CheckCircleIcon,
  CheckFatIcon,
  CheckIcon,
  CheckSquareIcon,
  ChefHatIcon,
  CigaretteIcon,
  CigaretteSlashIcon,
  CircleFilledIcon,
  CircleIcon,
  ClipboardTextIcon,
  ClockClockwiseIcon,
  ClockCounterClockwiseIcon,
  ClockIcon,
  ClosedCaptioningIcon,
  CloudFogIcon,
  CloudIcon,
  CloudLightningIcon,
  CloudMoonIcon,
  CloudRainIcon,
  CloudSnowIcon,
  CloudSunIcon,
  CloverIcon,
  ClubIcon,
  CoatHangerIcon,
  CoinIcon,
  CompassIcon,
  ConfettiIcon,
  CopyIcon,
  CopySimpleIcon,
  CowIcon,
  CreditCardIcon,
  CrosshairIcon,
  CrosshairSimpleIcon,
  CrownIcon,
  CrownSimpleIcon,
  CurrencyCircleDollarIcon,
  CurrencyDollarIcon,
  CurrencyEurIcon,
  CurrencyJpyIcon,
  CurrencyKrwIcon,
  CursorIcon,
  DivideIcon,
  DogIcon,
  DotsThreeCircleHorizontalIcon,
  DotsThreeCircleVerticalIcon,
  DotsThreeHortizontalIcon,
  DotsThreeVerticalIcon,
  DownloadIcon,
  DressIcon,
  DropIcon,
  DropSimpleIcon,
  EarIcon,
  EarSlashIcon,
  EarthIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  EqualsIcon,
  ExamIcon,
  ExclamationMarkIcon,
  ExportIcon,
  EyeClosedIcon,
  EyeIcon,
  EyeSlashIcon,
  EyeglassesIcon,
  FastForwardIcon,
  FileIcon,
  FilmReelIcon,
  FilmSlateIcon,
  FingerprintIcon,
  FireExtinguisherIcon,
  FireIcon,
  FireSimpleIcon,
  FishIcon,
  FlagIcon,
  FlagPennantIcon,
  FlashIcon,
  FloppyDiskIcon,
  FlowerIcon,
  FlyingSaucerIcon,
  FolderIcon,
  FolderOpenIcon,
  ForkKnifeIcon,
  FunnelIcon,
  FunnelXIcon,
  GameControllerIcon,
  GhostIcon,
  GiftIcon,
  GlobelIcon,
  GpsFixIcon,
  GpsIcon,
  GreaterThanIcon,
  GreaterThanOrEqualIcon,
  HashIcon,
  HeadphonesIcon,
  HeartIcon,
  HighlighterIcon,
  HourglassHighIcon,
  HourglassIcon,
  HourglassLowIcon,
  HouseIcon,
  HouseSimpleIcon,
  IceCreamIcon,
  ImageIcon,
  InfinityIcon,
  InfoIcon,
  KeyIcon,
  KeyholeIcon,
  KnifeIcon,
  LeafIcon,
  LecternIcon,
  LessThanIcon,
  LessThanOrEqualIcon,
  LinkIcon,
  LinkSimpleBreakIcon,
  LinkSimpleHorizontalBreakIcon,
  LinkSimpleHorizontalIcon,
  LinkSimpleIcon,
  ListHeartIcon,
  ListSearchIcon,
  ListStarIcon,
  LockIcon,
  LockOpenIcon,
  LockSimpleIcon,
  LockSimpleOpenIcon,
  MapIcon,
  MapPinAreaIcon,
  MapPinIcon,
  MapPinSimpleAreaIcon,
  MapPinSimpleIcon,
  MaskHappyIcon,
  MaskSadIcon,
  MathOperationsIcon,
  MedalIcon,
  MedalMilitaryIcon,
  MegaphoneIcon,
  MicrophoneIcon,
  MicrophoneSlashIcon,
  MicrophoneStageIcon,
  MinusIcon,
  MoneyIcon,
  MoonIcon,
  MoonStarsIcon,
  MouseIcon,
  MouseScrollIcon,
  MouseSimpleIcon,
  MusicNotesIcon,
  NavigationArrowIcon,
  NoteBlankIcon,
  NoteIcon,
  NotePencilIcon,
  NumberCircleEightIcon,
  NumberCircleFiveIcon,
  NumberCircleFourIcon,
  NumberCircleNineIcon,
  NumberCircleOneIcon,
  NumberCircleSevenIcon,
  NumberCircleSixIcon,
  NumberCircleThreeIcon,
  NumberEightIcon,
  NumberFiveIcon,
  NumberFourIcon,
  NumberNineIcon,
  NumberOneIcon,
  NumberSevenIcon,
  NumberSixIcon,
  NumberSquareEightIcon,
  NumberSquareFiveIcon,
  NumberSquareFourIcon,
  NumberSquareNineIcon,
  NumberSquareOneIcon,
  NumberSquareSevenIcon,
  NumberSquareSixIcon,
  NumberSquareThreeIcon,
  NumberSquareTwoIcon,
  NumberSquareZeroIcon,
  NumberThreeIcon,
  NumberTwoIcon,
  NumberZeroIcon,
  PackageIcon,
  PaintBrushBroadIcon,
  PaintBrushIcon,
  PaintIcon,
  PaletteIcon,
  PaperPlaneRightIcon,
  PaperPlaneTiltIcon,
  PaperPlaneTopIcon,
  PaperclipHorizontalIcon,
  PaperclipIcon,
  PauseIcon,
  PawPrintIcon,
  PenNibIcon,
  PenNibStraightIcon,
  PencilIcon,
  PencilLineIcon,
  PencilSlashIcon,
  PercentIcon,
  PhoneCallIcon,
  PhoneIcon,
  PingPongIcon,
  PlanetIcon,
  PlantIcon,
  PlayIcon,
  PlayPauseIcon,
  PlaylistIcon,
  PlusIcon,
  PowerIcon,
  PrinterIcon,
  ProhibitIcon,
  PushPinIcon,
  PushPinSimpleIcon,
  PushPinSimpleSlashIcon,
  PushPinSlashIcon,
  QuestionIcon,
  QuestionMarkIcon,
  QueueIcon,
  RabbitIcon,
  RacquetIcon,
  RainbowIcon,
  RepeatIcon,
  RepeatOnceIcon,
  RewindIcon,
  RocketIcon,
  RocketLaunchIcon,
  SealCheckIcon,
  SealIcon,
  SearchIcon,
  SearchMinusIcon,
  SearchPlusIcon,
  SettingIcon,
  ShareFatIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShieldIcon,
  ShoppingCartSimpleIcon,
  ShuffleIcon,
  SirenIcon,
  SkipBackIcon,
  SkipForwardIcon,
  SkullIcon,
  SlidersHorizontalIcon,
  SlidersVerticalIcon,
  SnowflakeIcon,
  SpeakerHighIcon,
  SpeakerIcon,
  SpeakerLowIcon,
  SpeakerNoneIcon,
  SpeakerSlashIcon,
  SpeakerXIcon,
  SpiralIcon,
  StarIcon,
  StopIcon,
  StorefrontIcon,
  StudentIcon,
  SuitcaseIcon,
  SuitcaseRollingIcon,
  SunDimIcon,
  SunHorizonIcon,
  SunIcon,
  SunglassesIcon,
  TShirtIcon,
  TagIcon,
  TelevisionIcon,
  TennisBallIcon,
  TentIcon,
  TextAUnderlineIcon,
  ThermometerColdIcon,
  ThermometerHotIcon,
  ThermometerIcon,
  ThermometerSimpleIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TimerIcon,
  ToggleLeftIcon,
  ToggleRightIcon,
  TrainIcon,
  TranslateIcon,
  TrashIcon,
  TreeEvergreenIcon,
  TreeIcon,
  TrophyIcon,
  TruckIcon,
  TunderIcon,
  UmbrellaIcon,
  UploadIcon,
  VideoCameraIcon,
  VideoCameraSlashIcon,
  VideoIcon,
  VolleyballIcon,
  WarningCircleIcon,
  WarningIcon,
  WatchIcon,
  WaveformIcon,
  WaveformSlashIcon,
  WavesIcon,
  WindIcon,
  WrenchIcon,
  XIcon,
  CalendarBlankFilledIcon,
  CheckCircleFilledIcon,
  InfoFilledIcon,
  WarningFilledIcon,
  WarningCircleFilledIcon,
  BabyIcon,
  EyesIcon,
  FootprintsIcon,
  GenderFemaleIcon,
  GenderMaleIcon,
  HandIcon,
  HandGrabbingIcon,
  HandPalmIcon,
  HandPeaceIcon,
  HandPointingIcon,
  HandsClappingIcon,
  HandshakeIcon,
  HandsPrayingIcon,
  IdentificationBadgeIcon,
  IdentificationCardIcon,
  PersonIcon,
  PersonArmsSpreadIcon,
  PersonSimpleIcon,
  PersonSimpleRunIcon,
  SmileyIcon,
  SmileyAngryIcon,
  SmileyBlankIcon,
  SmileyMehIcon,
  SmileyMeltingIcon,
  SmileySadIcon,
  SmileyWinkIcon,
  SmileyXEyesIcon,
  UserIcon,
  UserCircleIcon,
  UserFocusIcon,
  UserRectangleIcon,
  UsersIcon,
  UsersFourIcon,
  UserSquareIcon,
  UsersThreeIcon,
  UserSwitchIcon,
  WheelchairIcon,
  ArrowCounterClockwiseFilledIcon,
  ArrowClockwiseFilledIcon,
  ArrowUpFilledIcon,
  ArrowDownFilledIcon,
  ArrowLeftFilledIcon,
  ArrowRightFilledIcon,
  CaretUpFilledIcon,
  CaretDownFilledIcon,
  CaretLeftFilledIcon,
  CaretRightFilledIcon,
  CaretDoubleUpFilledIcon,
  CaretDoubleDownFilledIcon,
  CaretDoubleLeftFilledIcon,
  CaretDoubleRightFilledIcon,
  ArrowFatUpFilledIcon,
  ArrowFatDownFilledIcon,
  ArrowFatLeftFilledIcon,
  ArrowFatRightFilledIcon,
  ArrowsHorizontalFilledIcon,
  ArrowsVerticalFilledIcon,
  ArrowsLeftRightFilledIcon,
  ArrowsDownUpFilledIcon,
  ArrowsClockwiseFilledIcon,
  CaretCircleUpDownFilledIcon,
  CaretCircleUpFilledIcon,
  CaretCircleRightFilledIcon,
  CaretCircleDownFilledIcon,
  CaretCircleLeftFilledIcon,
  UploadFilledIcon,
  ToggleRightFilledIcon,
  ToggleLeftFilledIcon,
  PowerFilledIcon,
  MouseFilledIcon,
  MouseSimpleFilledIcon,
  MouseScrollFilledIcon,
  SearchFilledIcon,
  SearchPlusFilledIcon,
  SearchMinusFilledIcon,
  ListStarFilledIcon,
  ListHeartFilledIcon,
  ListSearchFilledIcon,
  LinkSimpleHorizontalBreakFilledIcon,
  LinkSimpleHorizontalFilledIcon,
  LinkSimpleBreakFilledIcon,
  LinkSimpleFilledIcon,
  TunderFilledIcon,
  BulbFilledIcon,
  SettingFilledIcon,
  FlashFilledIcon,
  DownloadFilledIcon,
  DotsThreeVerticalFilledIcon,
  DotsThreeCircleVerticalFilledIcon,
  DotsThreeCircleHorizontalFilledIcon,
  DotsThreeHortizontalFilledIcon,
  BackspaceFilledIcon,
  BellFilledIcon,
  BellRingingFilledIcon,
  BellSlashFilledIcon,
  CheckFilledIcon,
  CheckFatFilledIcon,
  CheckSquareFilledIcon,
  CursorFilledIcon,
  LinkFilledIcon,
} from '.'
import { NumberCircleTwo } from './generated/NumberCircleTwo'
import { NumberCircleZero } from './generated/NumberCircleZero'
import { IconProps } from './icon.types'

export const arrowIcons: { [key: string]: React.ComponentType<IconProps> } = {
  ArrowCounterClockwise: ArrowCounterClockwiseIcon,
  ArrowCounterClockwiseFilled: ArrowCounterClockwiseFilledIcon,
  ArrowClockwise: ArrowClockwiseIcon,
  ArrowClockwiseFilled: ArrowClockwiseFilledIcon,
  ArrowUp: ArrowUpIcon,
  ArrowUpFilled: ArrowUpFilledIcon,
  ArrowDown: ArrowDownIcon,
  ArrowDownFilled: ArrowDownFilledIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowLeftFilled: ArrowLeftFilledIcon,
  ArrowRight: ArrowRightIcon,
  ArrowRightFilled: ArrowRightFilledIcon,
  CaretUp: CaretUpIcon,
  CaretUpFilled: CaretUpFilledIcon,
  CaretDown: CaretDownIcon,
  CaretDownFilled: CaretDownFilledIcon,
  CaretLeft: CaretLeftIcon,
  CaretLeftFilled: CaretLeftFilledIcon,
  CaretRight: CaretRightIcon,
  CaretRightFilled: CaretRightFilledIcon,
  CaretDoubleUp: CaretDoubleUpIcon,
  CaretDoubleUpFilled: CaretDoubleUpFilledIcon,
  CaretDoubleDown: CaretDoubleDownIcon,
  CaretDoubleDownFilled: CaretDoubleDownFilledIcon,
  CaretDoubleLeft: CaretDoubleLeftIcon,
  CaretDoubleLeftFilled: CaretDoubleLeftFilledIcon,
  CaretDoubleRight: CaretDoubleRightIcon,
  CaretDoubleRightFilled: CaretDoubleRightFilledIcon,
  ArrowFatUp: ArrowFatUpIcon,
  ArrowFatUpFilled: ArrowFatUpFilledIcon,
  ArrowFatDown: ArrowFatDownIcon,
  ArrowFatDownFilled: ArrowFatDownFilledIcon,
  ArrowFatLeft: ArrowFatLeftIcon,
  ArrowFatLeftFilled: ArrowFatLeftFilledIcon,
  ArrowFatRight: ArrowFatRightIcon,
  ArrowFatRightFilled: ArrowFatRightFilledIcon,
  ArrowsHorizontal: ArrowsHorizontalIcon,
  ArrowsHorizontalFilled: ArrowsHorizontalFilledIcon,
  ArrowsVertical: ArrowsVerticalIcon,
  ArrowsVerticalFilled: ArrowsVerticalFilledIcon,
  ArrowsLeftRight: ArrowsLeftRightIcon,
  ArrowsLeftFilledRight: ArrowsLeftRightFilledIcon,
  ArrowsDownUp: ArrowsDownUpIcon,
  ArrowsDownUpFilled: ArrowsDownUpFilledIcon,
  ArrowsClockwise: ArrowsClockwiseIcon,
  ArrowsClockwiseFilled: ArrowsClockwiseFilledIcon,
  CaretCircleUpDown: CaretCircleUpDownIcon,
  CaretCircleUpDownFilled: CaretCircleUpDownFilledIcon,
  CaretCircleUp: CaretCircleUpIcon,
  CaretCircleUpFilled: CaretCircleUpFilledIcon,
  CaretCircleDown: CaretCircleDownIcon,
  CaretCircleDownFilled: CaretCircleDownFilledIcon,
  CaretCircleLeft: CaretCircleLeftIcon,
  CaretCircleLeftFilled: CaretCircleLeftFilledIcon,
  CaretCircleRight: CaretCircleRightIcon,
  CaretCircleRightFilled: CaretCircleRightFilledIcon,
}

export const systemIcons: { [key: string]: React.ComponentType<IconProps> } = {
  Upload: UploadIcon,
  UploadFilled: UploadFilledIcon,
  ToggleRight: ToggleRightIcon,
  ToggleRightFilled: ToggleRightFilledIcon,
  ToggleLeft: ToggleLeftIcon,
  ToggleLeftFilled: ToggleLeftFilledIcon,
  Power: PowerIcon,
  PowerFilled: PowerFilledIcon,
  Mouse: MouseIcon,
  MouseFilled: MouseFilledIcon,
  MouseSimple: MouseSimpleIcon,
  MouseSimpleFilled: MouseSimpleFilledIcon,
  MouseScroll: MouseScrollIcon,
  MouseScrollFilled: MouseScrollFilledIcon,
  Search: SearchIcon,
  SearchFilled: SearchFilledIcon,
  SearchPlus: SearchPlusIcon,
  SearchPlusFilled: SearchPlusFilledIcon,
  SearchMinus: SearchMinusIcon,
  SearchMinusFilled: SearchMinusFilledIcon,
  ListStar: ListStarIcon,
  ListStarFilled: ListStarFilledIcon,
  ListHeart: ListHeartIcon,
  ListHeartFilled: ListHeartFilledIcon,
  ListSearch: ListSearchIcon,
  ListSearchFilled: ListSearchFilledIcon,
  LinkSimpleHorizontalBreak: LinkSimpleHorizontalBreakIcon,
  LinkSimpleHorizontalBreakFilled: LinkSimpleHorizontalBreakFilledIcon,
  LinkSimpleHorizontal: LinkSimpleHorizontalIcon,
  LinkSimpleHorizontalFilled: LinkSimpleHorizontalFilledIcon,
  LinkSimpleBreak: LinkSimpleBreakIcon,
  LinkSimpleBreakFilled: LinkSimpleBreakFilledIcon,
  LinkSimple: LinkSimpleIcon,
  LinkSimpleFilled: LinkSimpleFilledIcon,
  Link: LinkIcon,
  LinkFilled: LinkFilledIcon,
  Tunder: TunderIcon,
  TunderFilled: TunderFilledIcon,
  Bulb: BulbIcon,
  BulbFilled: BulbFilledIcon,
  Setting: SettingIcon,
  SettingFilled: SettingFilledIcon,
  Flash: FlashIcon,
  FlashFilled: FlashFilledIcon,
  Download: DownloadIcon,
  DownloadFilled: DownloadFilledIcon,
  DotsThreeVertical: DotsThreeVerticalIcon,
  DotsThreeVerticalFilled: DotsThreeVerticalFilledIcon,
  DotsThreeCircleVertical: DotsThreeCircleVerticalIcon,
  DotsThreeCircleVerticalFilled: DotsThreeCircleVerticalFilledIcon,
  DotsThreeCircleHorizontal: DotsThreeCircleHorizontalIcon,
  DotsThreeCircleHorizontalFilled: DotsThreeCircleHorizontalFilledIcon,
  DotsThreeHortizontal: DotsThreeHortizontalIcon,
  DotsThreeHortizontalFilled: DotsThreeHortizontalFilledIcon,
  Cursor: CursorIcon,
  CursorFilled: CursorFilledIcon,
  CheckSquare: CheckSquareIcon,
  CheckSquareFilled: CheckSquareFilledIcon,
  CheckFat: CheckFatIcon,
  CheckFatFilled: CheckFatFilledIcon,
  CheckCircle: CheckCircleIcon,
  CheckCircleFilled: CheckCircleFilledIcon,
  Check: CheckIcon,
  CheckFilled: CheckFilledIcon,
  BellSlash: BellSlashIcon,
  BellSlashFilled: BellSlashFilledIcon,
  BellRinging: BellRingingIcon,
  BellRingingFilled: BellRingingFilledIcon,
  Bell: BellIcon,
  BellFilled: BellFilledIcon,
  Backspace: BackspaceIcon,
  BackspaceFilled: BackspaceFilledIcon,
}

export const mediaIcons: { [key: string]: React.ComponentType<IconProps> } = {
  Airplay: AirplayIcon,
  Article: ArticleIcon,
  Camera: CameraIcon,
  ClosedCaptioning: ClosedCaptioningIcon,
  Ear: EarIcon,
  EarSlash: EarSlashIcon,
  FastForward: FastForwardIcon,
  FilmReel: FilmReelIcon,
  FilmSlate: FilmSlateIcon,
  Headphones: HeadphonesIcon,
  Image: ImageIcon,
  Microphone: MicrophoneIcon,
  MicrophoneSlash: MicrophoneSlashIcon,
  MicrophoneStage: MicrophoneStageIcon,
  MusicNotes: MusicNotesIcon,
  Pause: PauseIcon,
  Play: PlayIcon,
  PlayPause: PlayPauseIcon,
  Playlist: PlaylistIcon,
  Queue: QueueIcon,
  Repeat: RepeatIcon,
  RepeatOnce: RepeatOnceIcon,
  Rewind: RewindIcon,
  Shuffle: ShuffleIcon,
  SkipBack: SkipBackIcon,
  SkipForward: SkipForwardIcon,
  SlidersVertical: SlidersVerticalIcon,
  SlidersHorizontal: SlidersHorizontalIcon,
  Speaker: SpeakerIcon,
  SpeakerHigh: SpeakerHighIcon,
  SpeakerLow: SpeakerLowIcon,
  SpeakerNone: SpeakerNoneIcon,
  SpeakerSlash: SpeakerSlashIcon,
  SpeakerX: SpeakerXIcon,
  Stop: StopIcon,
  Television: TelevisionIcon,
  VideoCamera: VideoCameraIcon,
  VideoCameraSlash: VideoCameraSlashIcon,
  Waveform: WaveformIcon,
  WaveformSlash: WaveformSlashIcon,
}

export const communicationIcons: { [key: string]: React.ComponentType<IconProps> } = {
  AddressBook: AddressBookIcon,
  At: AtIcon,
  ChatSquare: ChatSquareIcon,
  ChatCircle: ChatCircleIcon,
  ChatCircleDots: ChatCircleDotsIcon,
  ChatCircleSlash: ChatCircleSlashIcon,
  ChatCircleText: ChatCircleTextIcon,
  ChatSquareDots: ChatSquareDotsIcon,
  ChatSquareSlash: ChatSquareSlashIcon,
  ChatSquareText: ChatSquareTextIcon,
  ChatsSquare: ChatsSquareIcon,
  ChatsCircle: ChatsCircleIcon,
  Envelope: EnvelopeIcon,
  EnvelopeOpen: EnvelopeOpenIcon,
  Export: ExportIcon,
  Hash: HashIcon,
  Megaphone: MegaphoneIcon,
  PaperPlaneTop: PaperPlaneTopIcon,
  PaperPlaneRight: PaperPlaneRightIcon,
  PaperPlaneTilt: PaperPlaneTiltIcon,
  Phone: PhoneIcon,
  PhoneCall: PhoneCallIcon,
  ShareFat: ShareFatIcon,
  Share: ShareIcon,
  Star: StarIcon,
  ThumbsDown: ThumbsDownIcon,
  ThumbsUp: ThumbsUpIcon,
  Translate: TranslateIcon,
}

export const designIcons: { [key: string]: React.ComponentType<IconProps> } = {
  Eye: EyeIcon,
  EyeSlash: EyeSlashIcon,
  EyeClosed: EyeClosedIcon,
  PaintBrushBroad: PaintBrushBroadIcon,
  PaintBrush: PaintBrushIcon,
  Highlighter: HighlighterIcon,
  TextAUnderline: TextAUnderlineIcon,
  PencilSlash: PencilSlashIcon,
  PencilLine: PencilLineIcon,
  Pencil: PencilIcon,
  PenNibStraight: PenNibStraightIcon,
  PenNib: PenNibIcon,
  Palette: PaletteIcon,
  Paint: PaintIcon,
  Circle: CircleIcon,
  CircleFilled: CircleFilledIcon,
}

export const educationIcons: { [key: string]: React.ComponentType<IconProps> } = {
  Bookmark: BookmarkIcon,
  Bookmarks: BookmarksIcon,
  BookOpen: BookOpenIcon,
  BookOpenText: BookOpenTextIcon,
  BookBookmark: BookBookmarkIcon,
  Video: VideoIcon,
  Student: StudentIcon,
  Lectern: LecternIcon,
  Exam: ExamIcon,
  Certificate: CertificateIcon,
  Books: BooksIcon,
}

export const travelIcons: { [key: string]: React.ComponentType<IconProps> } = {
  Truck: TruckIcon,
  Train: TrainIcon,
  Tent: TentIcon,
  SuitcaseRolling: SuitcaseRollingIcon,
  Suitcase: SuitcaseIcon,
  RocketLaunch: RocketLaunchIcon,
  Rocket: RocketIcon,
  NavigationArrow: NavigationArrowIcon,
  Map: MapIcon,
  MapPinSimpleArea: MapPinSimpleAreaIcon,
  MapPinSimple: MapPinSimpleIcon,
  MapPinArea: MapPinAreaIcon,
  MapPin: MapPinIcon,
  HouseSimple: HouseSimpleIcon,
  House: HouseIcon,
  GpsFix: GpsFixIcon,
  Gps: GpsIcon,
  Earth: EarthIcon,
  Globel: GlobelIcon,
  FlagPennant: FlagPennantIcon,
  Flag: FlagIcon,
  CrosshairSimple: CrosshairSimpleIcon,
  Crosshair: CrosshairIcon,
  Compass: CompassIcon,
  CarProfile: CarProfileIcon,
  Car: CarIcon,
  Bus: BusIcon,
  AirplaneTilt: AirplaneTiltIcon,
  Airplane: AirplaneIcon,
}

export const officeIcons: { [key: string]: React.ComponentType<IconProps> } = {
  Trash: TrashIcon,
  PushPinSlash: PushPinSlashIcon,
  PushPinSimpleSlash: PushPinSimpleSlashIcon,
  PushPinSimple: PushPinSimpleIcon,
  PushPin: PushPinIcon,
  Printer: PrinterIcon,
  PaperclipHorizontal: PaperclipHorizontalIcon,
  Paperclip: PaperclipIcon,
  NotePencil: NotePencilIcon,
  NoteBlank: NoteBlankIcon,
  Note: NoteIcon,
  FunnelX: FunnelXIcon,
  Funnel: FunnelIcon,
  FolderOpen: FolderOpenIcon,
  Folder: FolderIcon,
  FloppyDisk: FloppyDiskIcon,
  File: FileIcon,
  CopySimple: CopySimpleIcon,
  Copy: CopyIcon,
  ClipboardText: ClipboardTextIcon,
  Briefcase: BriefcaseIcon,
  BoxArrowUp: BoxArrowUpIcon,
  BoxArrowDown: BoxArrowDownIcon,
  Archive: ArchiveIcon,
}

export const securityIcons: { [key: string]: React.ComponentType<IconProps> } = {
  ExclamationMark: ExclamationMarkIcon,
  Fingerprint: FingerprintIcon,
  FireExtinguisher: FireExtinguisherIcon,
  Info: InfoIcon,
  InfoFilled: InfoFilledIcon,
  Key: KeyIcon,
  Keyhole: KeyholeIcon,
  Lock: LockIcon,
  LockOpen: LockOpenIcon,
  LockSimple: LockSimpleIcon,
  LockSimpleOpen: LockSimpleOpenIcon,
  Prohibit: ProhibitIcon,
  Question: QuestionIcon,
  QuestionMark: QuestionMarkIcon,
  Seal: SealIcon,
  SealCheck: SealCheckIcon,
  Shield: ShieldIcon,
  ShieldCheck: ShieldCheckIcon,
  Siren: SirenIcon,
  Warning: WarningIcon,
  WarningFilled: WarningFilledIcon,
  WarningCircle: WarningCircleIcon,
  WarningCircleFilled: WarningCircleFilledIcon,
}

export const timeIcons: { [key: string]: React.ComponentType<IconProps> } = {
  Alarm: AlarmIcon,
  Calendar: CalendarIcon,
  CalendarBlank: CalendarBlankIcon,
  CalendarBlankFilled: CalendarBlankFilledIcon,
  CalendarCheck: CalendarCheckIcon,
  CalendarDot: CalendarDotIcon,
  CalendarDots: CalendarDotsIcon,
  CalendarHeart: CalendarHeartIcon,
  Clock: ClockIcon,
  ClockClockwise: ClockClockwiseIcon,
  ClockCounterClockwise: ClockCounterClockwiseIcon,
  Hourglass: HourglassIcon,
  HourglassHigh: HourglassHighIcon,
  HourglassLow: HourglassLowIcon,
  Timer: TimerIcon,
  Watch: WatchIcon,
}

export const natureIcons: { [key: string]: React.ComponentType<IconProps> } = {
  Wind: WindIcon,
  Waves: WavesIcon,
  Umbrella: UmbrellaIcon,
  TreeEvergreen: TreeEvergreenIcon,
  Tree: TreeIcon,
  ThermometerSimple: ThermometerSimpleIcon,
  ThermometerHot: ThermometerHotIcon,
  ThermometerCold: ThermometerColdIcon,
  Thermometer: ThermometerIcon,
  SunHorizon: SunHorizonIcon,
  SunDim: SunDimIcon,
  Sun: SunIcon,
  Snowflake: SnowflakeIcon,
  Rainbow: RainbowIcon,
  Rabbit: RabbitIcon,
  Plant: PlantIcon,
  Planet: PlanetIcon,
  PawPrint: PawPrintIcon,
  MoonStars: MoonStarsIcon,
  Moon: MoonIcon,
  Leaf: LeafIcon,
  Flower: FlowerIcon,
  Fish: FishIcon,
  FireSimple: FireSimpleIcon,
  Fire: FireIcon,
  DropSimple: DropSimpleIcon,
  Drop: DropIcon,
  Dog: DogIcon,
  Cow: CowIcon,
  Clover: CloverIcon,
  CloudSun: CloudSunIcon,
  CloudSnow: CloudSnowIcon,
  CloudRain: CloudRainIcon,
  CloudMoon: CloudMoonIcon,
  CloudLightning: CloudLightningIcon,
  CloudFog: CloudFogIcon,
  Cloud: CloudIcon,
  Cat: CatIcon,
  Cactus: CactusIcon,
  Butterfly: ButterflyIcon,
  Bone: BoneIcon,
  Bird: BirdIcon,
}

export const commerceIcons: { [key: string]: React.ComponentType<IconProps> } = {
  Wrench: WrenchIcon,
  Tag: TagIcon,
  TShirt: TShirtIcon,
  Sunglasses: SunglassesIcon,
  Storefront: StorefrontIcon,
  ShoppingCartSimple: ShoppingCartSimpleIcon,
  Package: PackageIcon,
  Money: MoneyIcon,
  Knife: KnifeIcon,
  IceCream: IceCreamIcon,
  Gift: GiftIcon,
  ForkKnife: ForkKnifeIcon,
  Eyeglasses: EyeglassesIcon,
  Dress: DressIcon,
  CurrencyKrw: CurrencyKrwIcon,
  CurrencyJpy: CurrencyJpyIcon,
  CurrencyEur: CurrencyEurIcon,
  CurrencyDollar: CurrencyDollarIcon,
  CurrencyCircleDollar: CurrencyCircleDollarIcon,
  CreditCard: CreditCardIcon,
  Coin: CoinIcon,
  CoatHanger: CoatHangerIcon,
  CigaretteSlash: CigaretteSlashIcon,
  Cigarette: CigaretteIcon,
  ChefHat: ChefHatIcon,
  Binoculars: BinocularsIcon,
  Basket: BasketIcon,
  Barcode: BarcodeIcon,
  Balloon: BalloonIcon,
  Bag: BagIcon,
  BabyCarriage: BabyCarriageIcon,
}

export const gameIcons: { [key: string]: React.ComponentType<IconProps> } = {
  Volleyball: VolleyballIcon,
  Trophy: TrophyIcon,
  TennisBall: TennisBallIcon,
  Spiral: SpiralIcon,
  Skull: SkullIcon,
  Racquet: RacquetIcon,
  PingPong: PingPongIcon,
  MedalMilitary: MedalMilitaryIcon,
  Medal: MedalIcon,
  MaskSad: MaskSadIcon,
  MaskHappy: MaskHappyIcon,
  Heart: HeartIcon,
  Ghost: GhostIcon,
  GameController: GameControllerIcon,
  FlyingSaucer: FlyingSaucerIcon,
  CrownSimple: CrownSimpleIcon,
  Crown: CrownIcon,
  Confetti: ConfettiIcon,
  Club: ClubIcon,
  BoxingGlove: BoxingGloveIcon,
  BowlingBall: BowlingBallIcon,
  Bomb: BombIcon,
  Basketball: BasketballIcon,
  BaseballHelmet: BaseballHelmetIcon,
  Alien: AlienIcon,
}

export const mathIcons: { [key: string]: React.ComponentType<IconProps> } = {
  Calculator: CalculatorIcon,
  Divide: DivideIcon,
  Equals: EqualsIcon,
  GreaterThan: GreaterThanIcon,
  GreaterThanOrEqual: GreaterThanOrEqualIcon,
  Infinity: InfinityIcon,
  LessThan: LessThanIcon,
  LessThanOrEqual: LessThanOrEqualIcon,
  MathOperations: MathOperationsIcon,
  Minus: MinusIcon,
  X: XIcon,
  Plus: PlusIcon,
  Percent: PercentIcon,
  NumberCircleZero: NumberCircleZero,
  NumberCircleOne: NumberCircleOneIcon,
  NumberCircleTwo: NumberCircleTwo,
  NumberCircleThree: NumberCircleThreeIcon,
  NumberCircleFour: NumberCircleFourIcon,
  NumberCircleFive: NumberCircleFiveIcon,
  NumberCircleSix: NumberCircleSixIcon,
  NumberCircleSeven: NumberCircleSevenIcon,
  NumberCircleEight: NumberCircleEightIcon,
  NumberCircleNine: NumberCircleNineIcon,
  NumberZero: NumberZeroIcon,
  NumberOne: NumberOneIcon,
  NumberTwo: NumberTwoIcon,
  NumberThree: NumberThreeIcon,
  NumberFour: NumberFourIcon,
  NumberFive: NumberFiveIcon,
  NumberSix: NumberSixIcon,
  NumberSeven: NumberSevenIcon,
  NumberEight: NumberEightIcon,
  NumberNine: NumberNineIcon,
  NumberSquareOne: NumberSquareOneIcon,
  NumberSquareZero: NumberSquareZeroIcon,
  NumberSquareTwo: NumberSquareTwoIcon,
  NumberSquareThree: NumberSquareThreeIcon,
  NumberSquareFour: NumberSquareFourIcon,
  NumberSquareFive: NumberSquareFiveIcon,
  NumberSquareSix: NumberSquareSixIcon,
  NumberSquareSeven: NumberSquareSevenIcon,
  NumberSquareEight: NumberSquareEightIcon,
  NumberSquareNine: NumberSquareNineIcon,
}

export const personIcons: { [key: string]: React.ComponentType<IconProps> } = {
  Baby: BabyIcon,
  Eyes: EyesIcon,
  Footprints: FootprintsIcon,
  GenderFemale: GenderFemaleIcon,
  GenderMale: GenderMaleIcon,
  Hand: HandIcon,
  HandGrabbing: HandGrabbingIcon,
  HandPalm: HandPalmIcon,
  HandPeace: HandPeaceIcon,
  HandPointing: HandPointingIcon,
  HandsClapping: HandsClappingIcon,
  Handshake: HandshakeIcon,
  HandsPrayingIcon,
  IdentificationBadge: IdentificationBadgeIcon,
  IdentificationCard: IdentificationCardIcon,
  Person: PersonIcon,
  PersonArmsSpread: PersonArmsSpreadIcon,
  PersonSimple: PersonSimpleIcon,
  PersonSimpleRun: PersonSimpleRunIcon,
  Smiley: SmileyIcon,
  SmileyAngry: SmileyAngryIcon,
  SmileyBlank: SmileyBlankIcon,
  SmileyMeh: SmileyMehIcon,
  SmileyMelting: SmileyMeltingIcon,
  SmileySad: SmileySadIcon,
  SmileyWink: SmileyWinkIcon,
  SmileyXEyes: SmileyXEyesIcon,
  User: UserIcon,
  UserCircle: UserCircleIcon,
  UserFocus: UserFocusIcon,
  UserRectangle: UserRectangleIcon,
  Users: UsersIcon,
  UsersFour: UsersFourIcon,
  UserSquare: UserSquareIcon,
  UsersThree: UsersThreeIcon,
  UserSwitch: UserSwitchIcon,
  Wheelchair: WheelchairIcon,
}
