# Workflow name
name: 'Chromatic Deployment version 1.0.0'

on:
  pull_request:
    branches: [version/1.0.0]
    paths:
      - '**.stories.tsx'
  push:
    branches: [version/1.0.0]
    paths:
      - '**.stories.tsx'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set node linker to nodeModules
        run: yarn config set nodeLinker "node-modules"

      - name: Install dependencies
        run: yarn install --immutable --check-cache

      - name: Publish to Chromatic
        id: publish_chromatic_1
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN  }}
          buildScriptName: build:c
          onlyChanged: true

      - name: comment PR
        uses: thollander/actions-comment-pull-request@v1
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: '🚀 **storybook**: ${{ steps.publish_chromatic_1.outputs.storybookUrl }}'
